### PR TITLE
Fix for issue 219: NAN in the training graph after stoping.

### PR DESCRIPTION
**Pull request by Nacho114**
Fix for issue 219: NAN in the training graph after stoping.

Basically mid training we are able to stop training, however at this point onEpochEnd might be reached, and because of this the train accuracy is NAN, to fix the graph displaying NAN values and doing funny things I only update the graph if the values are not NAN. (seems like an easy reasonable fix).

I removed an intermediary `updateGraph` function, since the parameters were inverted in the function call, in the UI, validation accuracy was actually train accuracy and vice-versa. Since the function was redundant (and being used wrongly) to begin with I removed it and made explicit calls to updateTrainGraph, and updateValid...

I removed redundant code from the old interoperability feature.

Fixes 219

### CODE REVIEW

**Comment by Nacho114** [comment]
As a side note, I modified `src/components/building_frames/TrainingInformationFrame.vue`, and this was linted in the process. It seems that perhaps this was not done before. @tharvik should it not have been linted with the github actions? (Or maybe my own machine is not rightly set up? Although looking at the diff, it looks like the lint my machine did is the right thing.

**Comment by tharvik** [comment]
> As a side note, I modified `src/components/building_frames/TrainingInformationFrame.vue`, and this was linted in the process. It seems that perhaps this was not done before. @tharvik should it not have been linted with the github actions? (Or maybe my own machine is not rightly set up?

From [what I gathered](https://cli.vuejs.org/core-plugins/eslint.html), there is not linter in place for HTML/vue file. We can add a linter for that, such as [prettier](https://prettier.io/), to ensure that.

> Although looking at the diff, it looks like the lint my machine did is the right thing.

btw, you can mask the whitespace changes in GitHub when seeing the diff, by clicking on the "setting cog" on the same line as "review changes"

**Comment by Nacho114** [comment]
> > As a side note, I modified `src/components/building_frames/TrainingInformationFrame.vue`, and this was linted in the process. It seems that perhaps this was not done before. @tharvik should it not have been linted with the github actions? (Or maybe my own machine is not rightly set up?
> 
> From [what I gathered](https://cli.vuejs.org/core-plugins/eslint.html), there is not linter in place for HTML/vue file. We can add a linter for that, such as [prettier](https://prettier.io/), to ensure that.
> 
> > Although looking at the diff, it looks like the lint my machine did is the right thing.
> 
> btw, you can mask the whitespace changes in GitHub when seeing the diff, by clicking on the "setting cog" on the same line as "review changes"

thanks for the tip! 

As for the linting, we are using plugin:vue/essential (see [here](https://github.com/epfml/disco/blob/develop/mobile-browser-based-version/.eslintrc.json), I thought this would also deal with html.

**Comment by tharvik** [comment]
> we are using plugin:vue/essential, I thought this would also deal with html.

Héhé, just found smth: replace `plugin:vue/essential` by `plugin:vue/recommended`, that does the trick :)

**Comment by Nacho114** [comment]
> `recommended`

Ah nice, I'll add this to this PR then. thanks :)

**Comment by Nacho114** [comment]
Actually I'll do a separate PR for this since a lot of files will be linted due to this change.

**Review by tharvik — APPROVED** [review]

**Pull request merged**
