### PR TITLE
UI: Change DeAI name to Disco

### PR DESCRIPTION
**Pull request by gozgun**
Changed DeAI and FeAI project names and links to Disco.

### CODE REVIEW

**Comment by martinjaggi** [comment]
thanks, looking nice!

**Comment by Nacho114** [comment]
Let's pimp the readme with some emojis 🪩 ! (Actually, you can also add some to the website if it seems appropriate, it seems all the cool kids do it these days.

⚙ ⚔🧪🗓⚙🛠📆📝📦🧙‍♂️🧛🦸‍♂️🧑‍🦯💡🤺🏋🤹‍♂️🧘🦍

🦊🕊🦚🐢🐬🐝🦠🌹🌻🌱🌵🍀🍉🍎🍓🥝🥥🧅

🧀🍕🍿🍥🥡🍼☕🍵🧉🌍🧭🏔🌋🏛🏗🏯🏰🗽

⛺🎢🚂🚔🚜🏎⛽🛑🚧⚓🚀⌛⏱⭐☁🌈🌀 

⚡❄🔥💧🌊🎃🎁🏆⚽🎯🔮🎲🧩🧸🪩🧶👑⛑

💎🔔🎙🎛🎹💾🎞🔍📖🏷💰✉✏🗑🛡🧰🧲🧬

📡🩻🚽🚿🛁🧻🧽⛔♾❓♻⭕🏴‍☠️👔

**Comment by Nacho114** [comment]
Looks good, before we merge I will still do two things here:

- Amend the ARCHITECTURE.md to reflect the newest architecture.

**Review by Nacho114 — APPROVED** [review]
Looks good, added some more stuff to readme + type fix

**Pull request merged**
