### PR TITLE
UI: Update Sidebar

### LINKED ISSUE #249: UI: Update Sidebar
Sidebar will contain plain texts rather than icons, Disco logo and new page names.
Footer will be moved to the sidebar.

### PR DESCRIPTION
**Pull request by gozgun**
This is mainly a cosmetic change with no routing updates.
Added new page titles to the sidebar, moved the footer to the sidebar for visibility reasons.
New features with this PR are active page's name on the sidebar is highlighed and pointer cursor is shown when hovering over a page title on the sidebar.

TODO:
- Remove unused icons
- Add Disco logo to the sidebar
- Update router addresses to the pages

resim

### CODE REVIEW

**Comment by Nacho114** [comment]
Nice!

How about changing `Find out more` to `Learn more`? It could also perhaps be in the lower section, maybe above `About Us` .

**Comment by gozgun** [comment]
> 
I agree that a name change is necessary. However, Learn More and Find Out More both sound as if the page contains further information rather than a tutorial. 

And if we move it towards the bottom, it is not as visible for new comers who dont know the site well. (ie. eyes would naturally follow a top to bottom path, at least mine do 😄  ).

**Comment by Nacho114** [comment]
> > 
> 
> I agree that a name change is necessary. However, Learn More and Find Out More both sound as if the page contains further information rather than a tutorial.
> 
> And if we move it towards the bottom, it is not as visible for new comers who dont know the site well. (ie. eyes would naturally follow a top to bottom path, at least mine do smile ).

I see, but if it's a tutorial should we not just call it `tutorial`?

**Comment by gozgun** [comment]
> > > 
> > 
> > 
> > I agree that a name change is necessary. However, Learn More and Find Out More both sound as if the page contains further information rather than a tutorial.
> > And if we move it towards the bottom, it is not as visible for new comers who dont know the site well. (ie. eyes would naturally follow a top to bottom path, at least mine do smile ).
> 
> I see, but if it's a tutorial should we not just call it `tutorial`?

Yes, Tutorial is a great name!

**Comment by s314cy** [comment]
discussed with @gozgun, this PR is stale w.r.t her more recent ones :)

**Pull request closed without merging**
